
set_property PACKAGE_PIN V17 [get_ports {switches_i[0]}]
set_property PACKAGE_PIN V16 [get_ports {switches_i[1]}]
set_property PACKAGE_PIN W16 [get_ports {switches_i[2]}]
set_property PACKAGE_PIN W17 [get_ports {switches_i[3]}]
set_property PACKAGE_PIN W15 [get_ports {switches_i[4]}]
set_property PACKAGE_PIN V15 [get_ports {switches_i[5]}]
set_property PACKAGE_PIN W14 [get_ports {switches_i[6]}]
#set_property PACKAGE_PIN W13 [get_ports {switches_i[7]}]
#set_property PACKAGE_PIN V2  [get_ports {switches_i[8]}]
#set_property PACKAGE_PIN T3  [get_ports {switches_i[9]}]
#set_property PACKAGE_PIN T2  [get_ports {switches_i[10]}]
#set_property PACKAGE_PIN R3  [get_ports {switches_i[11]}]
#set_property PACKAGE_PIN W2  [get_ports {switches_i[12]}]
#set_property PACKAGE_PIN U1  [get_ports {switches_i[13]}]
#set_property PACKAGE_PIN T1  [get_ports {switches_i[14]}]
#set_property PACKAGE_PIN R2  [get_ports {switches_i[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switches_i[*]}]
