
#set_property PACKAGE_PIN U16 [get_ports {leds_o[0]}]
#set_property PACKAGE_PIN E19 [get_ports {leds_o[1]}]
#set_property PACKAGE_PIN U19 [get_ports {leds_o[2]}]
#set_property PACKAGE_PIN V19 [get_ports {leds_o[3]}]
#set_property PACKAGE_PIN W18 [get_ports {leds_o[4]}]
#set_property PACKAGE_PIN U15 [get_ports {leds_o[5]}]
#set_property PACKAGE_PIN U14 [get_ports {leds_o[6]}]
#set_property PACKAGE_PIN V14 [get_ports {leds_o[7]}]
#set_property PACKAGE_PIN V13 [get_ports {leds_o[8]}]
#set_property PACKAGE_PIN V3  [get_ports {leds_o[9]}]
#set_property PACKAGE_PIN W3  [get_ports {leds_o[10]}]
#set_property PACKAGE_PIN U3  [get_ports {leds_o[11]}]
#set_property PACKAGE_PIN P3  [get_ports {leds_o[12]}]
#set_property PACKAGE_PIN N3  [get_ports {leds_o[13]}]
#set_property PACKAGE_PIN P1  [get_ports {leds_o[14]}]
#set_property PACKAGE_PIN L1  [get_ports {leds_o[15]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[*]}]
